// Embeds the vendored harness into the compiled bcode binary.
//
// The build script (`packages/opencode/script/build.ts`) calls
// `createEmbeddedHarnessBundle()` and plumbs the result into
// `Bun.build({ files: { "bcode-harness.gen.ts": <result> } })`. The generated
// virtual module exports `{ "<rel>": "<bunfs path>" }` for every harness file.
// `harness.ts` reads it lazily in compiled mode and extracts the files to a
// per-version cache dir on first use (decisions.md §4.6).
//
// The walk is glob-driven (not hand-enumerated): when skill files leave the
// repo for the cloud-fetch architecture (decisions.md §4.7) the embed shrinks
// automatically with no script change. Excludes mirror `harness/.gitignore`
// so local artifacts (`.venv/`, `__pycache__/`, `*.egg-info/`, etc.) never
// land in the binary.

import path from "path"
import { fileURLToPath } from "url"

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const HARNESS_DIR = path.resolve(__dirname, "..", "harness")

const ignored = [
  new Bun.Glob("**/__pycache__/**"),
  new Bun.Glob("**/.venv/**"),
  new Bun.Glob("**/*.egg-info/**"),
  new Bun.Glob("**/*.pyc"),
  new Bun.Glob("**/*.log"),
  new Bun.Glob("**/.env"),
  new Bun.Glob("**/uv.lock"),
]

export const createEmbeddedHarnessBundle = async (buildCwd: string) => {
  console.log("Embedding harness files into the binary")
  const files = (await Array.fromAsync(new Bun.Glob("**/*").scan({ cwd: HARNESS_DIR, dot: true })))
    .map((file) => file.replaceAll("\\", "/"))
    .filter((file) => !ignored.some((g) => g.match(file)))
    .sort()

  console.log(`Embedding ${files.length} harness files`)

  const imports = files.map((file, i) => {
    const spec = path.relative(buildCwd, path.join(HARNESS_DIR, file)).replaceAll("\\", "/")
    return `import file_${i} from ${JSON.stringify(spec.startsWith(".") ? spec : `./${spec}`)} with { type: "file" };`
  })
  const entries = files.map((file, i) => `  ${JSON.stringify(file)}: file_${i},`)
  return [
    `// Auto-generated by packages/bcode-browser/script/embed-harness.ts`,
    `// Maps "<rel>" -> bunfs path for every embedded harness file.`,
    ...imports,
    `export default {`,
    ...entries,
    `} as Record<string, string>`,
  ].join("\n")
}
