// Embeds the vendored harness into the compiled bcode binary.
//
// The build script (`packages/opencode/script/build.ts`) calls
// `createEmbeddedHarnessBundle()` and plumbs the result into
// `Bun.build({ files: { "bcode-harness.gen.ts": <result> } })`. The generated
// virtual module exports `{ "<rel>": "<bunfs path>" }` for every harness file
// plus a content-hash `buildHash` used as the on-disk extraction sentinel.
// `harness.ts` reads it in compiled mode and extracts the files to
// `<dataDir>/harness/` on session start, skipping when the sentinel matches.
//
// The walk is glob-driven (not hand-enumerated): when skill files leave the
// repo for the cloud-fetch architecture (decisions.md §4.7) the embed shrinks
// automatically with no script change. Excludes mirror `harness/.gitignore`
// so local artifacts (`.venv/`, `__pycache__/`, `*.egg-info/`, etc.) never
// land in the binary.

import crypto from "crypto"
import fs from "fs/promises"
import path from "path"
import { fileURLToPath } from "url"

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const HARNESS_DIR = path.resolve(__dirname, "..", "harness")

const ignored = [
  new Bun.Glob("**/__pycache__/**"),
  new Bun.Glob("**/.venv/**"),
  new Bun.Glob("**/*.egg-info/**"),
  new Bun.Glob("**/*.pyc"),
  new Bun.Glob("**/*.log"),
  new Bun.Glob("**/.env"),
  new Bun.Glob("**/uv.lock"),
]

// SHA-256 over (rel + NUL + content) for each file in sorted order. Stable
// across builds when content is identical, so warm launches skip extraction.
const computeBuildHash = async (files: string[]) => {
  const hash = crypto.createHash("sha256")
  for (const rel of files) {
    hash.update(rel)
    hash.update("\0")
    hash.update(await fs.readFile(path.join(HARNESS_DIR, rel)))
  }
  return hash.digest("hex")
}

export const createEmbeddedHarnessBundle = async (buildCwd: string) => {
  console.log("Embedding harness files into the binary")
  const files = (await Array.fromAsync(new Bun.Glob("**/*").scan({ cwd: HARNESS_DIR, dot: true })))
    .map((file) => file.replaceAll("\\", "/"))
    .filter((file) => !ignored.some((g) => g.match(file)))
    .sort()

  console.log(`Embedding ${files.length} harness files`)
  const buildHash = await computeBuildHash(files)

  const imports = files.map((file, i) => {
    const spec = path.relative(buildCwd, path.join(HARNESS_DIR, file)).replaceAll("\\", "/")
    return `import file_${i} from ${JSON.stringify(spec.startsWith(".") ? spec : `./${spec}`)} with { type: "file" };`
  })
  const entries = files.map((file, i) => `  ${JSON.stringify(file)}: file_${i},`)
  return [
    `// Auto-generated by packages/bcode-browser/script/embed-harness.ts`,
    `// Maps "<rel>" -> bunfs path for every embedded harness file.`,
    ...imports,
    `export const buildHash = ${JSON.stringify(buildHash)}`,
    `export default {`,
    ...entries,
    `} as Record<string, string>`,
  ].join("\n")
}
