// Skills directory resolver.
//
// Skills are always materialized to `<dataDir>/skills/` so the agent reads
// from a stable absolute path on every platform. During materialization,
// `{{SKILLS_DIR}}` placeholders inside `*.md` files are replaced with the
// target absolute path so cross-references in BROWSER.md (e.g. "read
// `{{SKILLS_DIR}}/cloud-browser.md`") resolve to a path the agent can use.
//
// Two packaging modes feed the materializer:
//
// 1. Dev mode — `import.meta.url` resolves to `packages/bcode-browser/src/`;
//    source skills live at the sibling `../skills/`. The hash is computed
//    over the on-disk source files so edits during dev iteration trigger
//    re-extraction on the next launch.
//
// 2. Compiled mode — running from a `bun build --compile` binary.
//    `import.meta.dir` lives under `/$bunfs/` (or `B:/~BUN/` on Windows), a
//    read-only virtual filesystem the agent's `read` tool can't see in a
//    useful path shape. We use the embed map generated by
//    `script/embed-skills.ts` and its precomputed `buildHash`.
//
// In both modes a content-hash sentinel at `<dataDir>/skills/.bcode-build`
// records the bundle + target path that produced the tree; warm launches
// stat-and-skip when both match. Including the target path in the sentinel
// guards against a stale tree if `dataDir` ever changes between launches.
//
// Skills are read-only baseline: every launch overwrites the on-disk tree
// (no agent-editable surface). The agent's editable surface is
// `<projectDir>/.bcode/agent-workspace/`, per-project, never here.

import crypto from "crypto"
import fs from "fs/promises"
import path from "path"
import { fileURLToPath } from "url"

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const isCompiled = (() => {
  const d = __dirname.replaceAll("\\", "/")
  return d.startsWith("/$bunfs/") || d.startsWith("B:/~BUN/")
})()
const DEV_SKILLS_DIR = path.resolve(__dirname, "..", "skills")
const SENTINEL_NAME = ".bcode-build"
const PLACEHOLDER = "{{SKILLS_DIR}}"

// Static path so the agent permission glob can use a stable absolute path.
export const skillsDir = (dataDir: string) => path.join(dataDir, "skills")

const readSentinel = async (dir: string) => {
  try { return await fs.readFile(path.join(dir, SENTINEL_NAME), "utf8") }
  catch { return null }
}

// `.md` files get template substitution; everything else is copied byte-for-
// byte. Substitution operates on the raw bytes rather than a UTF-8 round-trip
// to keep non-Markdown assets (images, binary fixtures) untouched if the
// skills tree ever grows beyond Markdown.
const writeSkillFile = async (dest: string, content: Uint8Array, target: string) => {
  await fs.mkdir(path.dirname(dest), { recursive: true })
  if (!dest.endsWith(".md") || !indexOfPlaceholder(content)) {
    await Bun.write(dest, content)
    return
  }
  const text = new TextDecoder("utf-8").decode(content).replaceAll(PLACEHOLDER, target)
  await fs.writeFile(dest, text, "utf8")
}

// Cheap byte-level pre-check so we skip the UTF-8 decode on files that don't
// need substitution. The placeholder is pure ASCII so a byte search is safe.
const PLACEHOLDER_BYTES = new TextEncoder().encode(PLACEHOLDER)
const indexOfPlaceholder = (buf: Uint8Array) => {
  outer: for (let i = 0; i + PLACEHOLDER_BYTES.length <= buf.length; i++) {
    for (let j = 0; j < PLACEHOLDER_BYTES.length; j++) {
      if (buf[i + j] !== PLACEHOLDER_BYTES[j]) continue outer
    }
    return true
  }
  return false
}

// Stable hash over (rel + NUL + content) for every source file in sorted
// order — same shape as the build-time hash in `script/embed-skills.ts`.
const computeDevHash = async (files: string[]) => {
  const hash = crypto.createHash("sha256")
  for (const rel of files) {
    hash.update(rel)
    hash.update("\0")
    hash.update(await fs.readFile(path.join(DEV_SKILLS_DIR, rel)))
  }
  return hash.digest("hex")
}

// Sentinel = "<bundleHash>:<target>". Including `target` invalidates the tree
// if `dataDir` (and therefore the substituted absolute path) ever changes.
const sentinelFor = (bundleHash: string, target: string) => `${bundleHash}:${target}`

const materializeFromSource = async (target: string): Promise<string> => {
  const files = (await Array.fromAsync(new Bun.Glob("**/*").scan({ cwd: DEV_SKILLS_DIR })))
    .map((f) => f.replaceAll("\\", "/"))
    .sort()
  const bundleHash = await computeDevHash(files)
  const sentinel = sentinelFor(bundleHash, target)
  if ((await readSentinel(target)) === sentinel) return target

  await fs.mkdir(target, { recursive: true })
  await Promise.all(
    files.map(async (rel) => {
      const buf = await fs.readFile(path.join(DEV_SKILLS_DIR, rel))
      await writeSkillFile(path.join(target, rel), buf, target)
    }),
  )
  await fs.writeFile(path.join(target, SENTINEL_NAME), sentinel, "utf8")
  return target
}

const materializeFromEmbed = async (target: string): Promise<string> => {
  // @ts-expect-error generated at build time
  const mod = await import("bcode-skills.gen.ts").catch(() => null)
  if (!mod) throw new Error("bcode-skills.gen.ts not found in compiled binary — was the build script updated?")
  const fileMap = mod.default as Record<string, string>
  const sentinel = sentinelFor(mod.buildHash as string, target)
  if ((await readSentinel(target)) === sentinel) return target

  await fs.mkdir(target, { recursive: true })
  await Promise.all(
    Object.entries(fileMap).map(async ([rel, bunfsPath]) => {
      const buf = new Uint8Array(await Bun.file(bunfsPath).arrayBuffer())
      await writeSkillFile(path.join(target, rel), buf, target)
    }),
  )
  await fs.writeFile(path.join(target, SENTINEL_NAME), sentinel, "utf8")
  return target
}

const extractCache = new Map<string, Promise<string>>()

export const resolveSkillsDir = (dataDir: string): Promise<string> => {
  const cached = extractCache.get(dataDir)
  if (cached) return cached
  const target = skillsDir(dataDir)
  const fresh = isCompiled ? materializeFromEmbed(target) : materializeFromSource(target)
  extractCache.set(dataDir, fresh)
  fresh.catch(() => {
    if (extractCache.get(dataDir) === fresh) extractCache.delete(dataDir)
  })
  return fresh
}

export * as Skills from "./skills"
